-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 16, 2022 at 11:55 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `projekt`
--

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `ime` varchar(50) NOT NULL,
  `prezime` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `autorizacija` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `ime`, `prezime`, `username`, `password`, `autorizacija`) VALUES
(1, 'grgur', 'adamec', 'grgur', '$2y$10$wNF6HwRCmBh7CAIKClkZuevAEZoCPLrKbsCDe/c/75IDrFWBVMw7G', 'admin'),
(4, 'marko', 'marko', 'marko', '$2y$10$FUg.D03p/KT/h7WY7D.g3u2CM26FEGgobhfXWbUkl2HBuWepdRoK2', ''),
(5, 'ljiljana', 'ljiljana', 'ljiljana', '$2y$10$U5uxVoNF9o91zMbsKnEHBuqBHOaHLj0lvLgCMV6nbsWLCaRPocaz2', ''),
(6, 'admin', 'admin', 'admin', '$2y$10$3I2QYFxSZ1oeJB/1LpyeKuFSDAn4LO.LovT69EIOxm0/AiOeRuoFW', 'admin'),
(7, 'user', 'user', 'user', '$2y$10$//0DZKrlmgwPBR3zOeW.l.c.LkEyox1zsQbBVkE3HS.e1JBSBmXL.', '');

-- --------------------------------------------------------

--
-- Table structure for table `vijest`
--

CREATE TABLE `vijest` (
  `id` int(11) NOT NULL,
  `naslov` varchar(255) NOT NULL,
  `kategorija` varchar(255) NOT NULL,
  `kratki_sadrzaj` varchar(255) NOT NULL,
  `sadrzaj` longtext NOT NULL,
  `slika` varchar(255) NOT NULL,
  `datum` varchar(255) NOT NULL,
  `vidljivost` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `vijest`
--

INSERT INTO `vijest` (`id`, `naslov`, `kategorija`, `kratki_sadrzaj`, `sadrzaj`, `slika`, `datum`, `vidljivost`) VALUES
(1, 'Moj prvi članak', 'SPORT', 'Ne znam al bit će dobar', 'Haha marko je kupio bombone aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'Slike/Jan_Vilímek_-_Karel_IV.jpg', '15.06.2022', 1),
(9, 'Moj drugi članak', 'POLITIKA', 'Ovaj ima dobar datum', 'Bla bla truč truč konj ide i jede travu\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra volutpat neque, ac pellentesque enim congue sed. Fusce sollicitudin, mauris viverra ornare efficitur, metus lacus egestas magna, nec dignissim diam orci vel diam. Aliquam fermentum risus ut ante commodo, vel bibendum lorem maximus. Duis tincidunt ex in varius blandit. Proin lectus dolor, porta in diam at, vulputate eleifend nisl. Nulla facilisi. Nullam non purus ex. Duis sed felis vitae magna venenatis luctus sed dignissim nunc. Quisque fringilla quis mi quis interdum. Nulla dictum risus sit amet urna consequat, sit amet semper purus sollicitudin. Maecenas sit amet enim non leo auctor commodo quis lacinia leo.\r\n\r\nProin et porttitor neque. Ut urna nisi, vestibulum ac nisl quis, ornare pretium quam. Donec at odio viverra erat dignissim hendrerit a eu erat. Proin luctus faucibus tellus sit amet dictum. Aenean tincidunt feugiat efficitur. Ut at justo posuere, porttitor sapien elementum, laoreet felis. Praesent dignissim pretium lectus non pulvinar. Aenean fermentum at erat nec luctus. Sed aliquam placerat volutpat. Quisque commodo mauris in cursus sagittis.', 'Slike/lastovo-panorama-01.jpg', '04.06.2022', 1),
(10, 'Marin u problemima', 'SPORT', 'Pogledajte Marinovu izjavu nakon gubitka od Britanskog reprezentativca Johna Bohemianrapsodyja', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra volutpat neque, ac pellentesque enim congue sed. Fusce sollicitudin, mauris viverra ornare efficitur, metus lacus egestas magna, nec dignissim diam orci vel diam. Aliquam fermentum risus ut ante commodo, vel bibendum lorem maximus. Duis tincidunt ex in varius blandit. Proin lectus dolor, porta in diam at, vulputate eleifend nisl. Nulla facilisi. Nullam non purus ex. Duis sed felis vitae magna venenatis luctus sed dignissim nunc. Quisque fringilla quis mi quis interdum. Nulla dictum risus sit amet urna consequat, sit amet semper purus sollicitudin. Maecenas sit amet enim non leo auctor commodo quis lacinia leo.\r\n\r\nProin et porttitor neque. Ut urna nisi, vestibulum ac nisl quis, ornare pretium quam. Donec at odio viverra erat dignissim hendrerit a eu erat. Proin luctus faucibus tellus sit amet dictum. Aenean tincidunt feugiat efficitur. Ut at justo posuere, porttitor sapien elementum, laoreet felis. Praesent dignissim pretium lectus non pulvinar. Aenean fermentum at erat nec luctus. Sed aliquam placerat volutpat. Quisque commodo mauris in cursus sagittis. \r\nMarin je izjavio da je John obični britanski konj koji ima zube ko morski pas al ne u dobrom smislu.', 'Slike/62315954-marin-cilic.jpg', '16.06.2022', 1),
(11, 'B.o.b izgubio parnicu', 'POLITIKA', 'Nakon 6 mjeseci suda sud naponokon donio presudu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/b.o.b.jpg', '16.06.2022', 1),
(12, 'John Cener osvoji WWP ', 'SPORT', 'Neki lažu, a neki ne', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra volutpat neque, ac pellentesque enim congue sed. Fusce sollicitudin, mauris viverra ornare efficitur, metus lacus egestas magna, nec dignissim diam orci vel diam. Aliquam fermentum risus ut ante commodo, vel bibendum lorem maximus. Duis tincidunt ex in varius blandit. Proin lectus dolor, porta in diam at, vulputate eleifend nisl. Nulla facilisi. Nullam non purus ex. Duis sed felis vitae magna venenatis luctus sed dignissim nunc. Quisque fringilla quis mi quis interdum. Nulla dictum risus sit amet urna consequat, sit amet semper purus sollicitudin. Maecenas sit amet enim non leo auctor commodo quis lacinia leo.\r\n\r\nProin et porttitor neque. Ut urna nisi, vestibulum ac nisl quis, ornare pretium quam. Donec at odio viverra erat dignissim hendrerit a eu erat. Proin luctus faucibus tellus sit amet dictum. Aenean tincidunt feugiat efficitur. Ut at justo posuere, porttitor sapien elementum, laoreet felis. Praesent dignissim pretium lectus non pulvinar. Aenean fermentum at erat nec luctus. Sed aliquam placerat volutpat. Quisque commodo mauris in cursus sagittis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra volutpat neque, ac pellentesque enim congue sed. Fusce sollicitudin, mauris viverra ornare efficitur, metus lacus egestas magna, nec dignissim diam orci vel diam. Aliquam fermentum risus ut ante commodo, vel bibendum lorem maximus. Duis tincidunt ex in varius blandit. Proin lectus dolor, porta in diam at, vulputate eleifend nisl. Nulla facilisi. Nullam non purus ex. Duis sed felis vitae magna venenatis luctus sed dignissim nunc. Quisque fringilla quis mi quis interdum. Nulla dictum risus sit amet urna consequat, sit amet semper purus sollicitudin. Maecenas sit amet enim non leo auctor commodo quis lacinia leo.\r\n\r\nProin et porttitor neque. Ut urna nisi, vestibulum ac nisl quis, ornare pretium quam. Donec at odio viverra erat dignissim hendrerit a eu erat. Proin luctus faucibus tellus sit amet dictum. Aenean tincidunt feugiat efficitur. Ut at justo posuere, porttitor sapien elementum, laoreet felis. Praesent dignissim pretium lectus non pulvinar. Aenean fermentum at erat nec luctus. Sed aliquam placerat volutpat. Quisque commodo mauris in cursus sagittis.', 'Slike/62315954-marin-cilic.jpg', '16.06.2022', 0),
(13, 'Benzin i dizel do 30kn/L', 'POLITIKA', 'Krah ekonomije, benzin i dizel preskupi i za Rimca', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/nafta.jpeg', '16.06.2022', 1),
(16, 'Jos jedna s Marinom', 'SPORT', 'kratki sadrzaj', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/62315954-marin-cilic.jpg', '16.06.2022', 0),
(17, 'BOB - tajna prehrane sportaša', 'SPORT', 'SPortski liječnici otkrili kako se hrane profesionalci', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/bob.jpg', '16.06.2022', 1),
(20, 'Ja sam vlak neki', 'POLITIKA', 'test test', 'jxbjkbabxakjbcakj', 'Slike/smrle.jpg', '12.06.2022', 0),
(24, 'Santi Cazorla - 9. Ballon d', 'SPORT', 'Španjolski maestro osvojio 9. Ballond d', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/Santi-Cazorla-Arsenal.jpg', '16.06.2022', 1),
(25, 'Bob - novi gradonačelnik?', 'POLITIKA', '\"Make Zagreb great again\"', 'Bob the Builder\r\nCan we fix it?\r\nBob the Builder\r\nYes, we can!\r\n\r\nScoop, Muck and Dizzy, and Rolly too\r\nLofty and Wendy join the crew\r\nBob and the gang have so much fun\r\nWorking together, they get the job done\r\n\r\nBob the Builder\r\nCan we fix it?\r\nBob the Builder\r\nYes, we can!\r\n\r\nPilchard and Bird, Travis and Spud\r\nPlaying together like good friends should\r\n\r\nBob the Builder\r\nCan we fix it?\r\nBob the Builder\r\nYes, we can!\r\n\r\nHey!\r\nTime to get busy, such a lot to do\r\nBuilding and fixing till it', 'Slike/thumb.jfif', '16.06.2022', 1),
(26, 'Borat službeno pobjedio', 'POLITIKA', 'Borat postao novi predsjednik Kazahstana nakon 3 kruga izbora', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/borat.jpg', '16.06.2022', 1),
(28, 'BOB postao najplaćeniji sport', 'SPORT', 'Pogledajte koliko zarađuju bob sportaši', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel fermentum purus, nec cursus felis. Maecenas quis rutrum quam. Vestibulum nec sollicitudin purus, et pharetra sapien. Curabitur bibendum, libero non gravida blandit, sem dui tempor turpis, non vestibulum enim tellus eu ex. Sed sem lacus, lobortis in vulputate ut, viverra ut ligula. Curabitur consequat purus a nibh congue volutpat. Duis feugiat, sapien ut tincidunt dapibus, ex turpis sodales elit, varius gravida tellus arcu pulvinar lorem. Cras lorem quam, maximus maximus turpis sed, posuere consequat ligula. Vestibulum a aliquam orci. Proin ut neque mollis, tincidunt elit ut, varius enim. Aenean convallis dignissim libero vitae laoreet. In hac habitasse platea dictumst. Mauris feugiat vel purus sed luctus. Duis tristique scelerisque elit, eu aliquet tellus pharetra in. Curabitur commodo molestie urna sed egestas. Aenean consequat mi vitae libero faucibus facilisis.\r\n\r\nNam vel lacus ut lacus eleifend lacinia ut vel enim. Fusce est nisi, aliquet eget rhoncus ut, gravida in nunc. Aliquam erat volutpat. Pellentesque sem turpis, ullamcorper id odio sed, placerat posuere urna. Nam tristique dictum neque et ullamcorper. Vestibulum nec leo ac diam efficitur laoreet. Curabitur sit amet viverra velit.\r\n\r\nPellentesque turpis tortor, scelerisque sit amet commodo vel, tempus non massa. Sed non volutpat erat. Pellentesque id justo est. Fusce accumsan, velit at convallis volutpat, lorem nisl tincidunt velit, in pretium ante sapien nec metus. Nulla facilisi. Sed pellentesque ipsum ac porta dignissim. Vestibulum consequat eu sapien a mollis. Donec auctor eget ante sit amet pharetra. Nulla congue mattis neque sed interdum. Vivamus metus sapien, finibus nec cursus in, iaculis varius leo.\r\n\r\nSed sapien purus, efficitur nec fringilla eget, dapibus a elit. Praesent ac justo eget magna interdum commodo non nec nisl. Vivamus venenatis vel diam nec aliquet. Aenean tellus arcu, vestibulum in mauris quis, ornare suscipit odio. Integer iaculis vehicula ligula. Maecenas eget laoreet tortor, in volutpat nisi. Pellentesque consectetur erat urna. Ut pellentesque magna in ex vehicula, non posuere mi hendrerit. Quisque sit amet lectus nunc. Mauris facilisis mollis eleifend. Nam quis pellentesque libero.\r\n\r\nPraesent a ante eu mi porta lobortis sagittis ut orci. Aliquam luctus mi vitae magna eleifend mattis. Ut eget posuere nunc, eget maximus erat. Sed in fermentum urna. Sed ultrices odio purus, vitae commodo velit maximus at. Nulla euismod nec velit quis varius. Sed elementum placerat consequat.', 'Slike/bobsled.jfif', '16.06.2022', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `vijest`
--
ALTER TABLE `vijest`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `vijest`
--
ALTER TABLE `vijest`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
COMMIT;
